namespace ApocMinimal.Models.GameActions;


public enum ActionCategory { Basic, Special }

/// <summary>
/// A single action an NPC can perform in a day.
/// NPCs perform up to 23 actions per day: max 3 special, rest basic.
/// </summary>
public class GameAction
{
    public int Id { get; set; }
    public string Name { get; set; } = "";
    public ActionCategory Category { get; set; }
    public string Description { get; set; } = "";

    /// <summary>Stamina cost (0–30).</summary>
    public double StaminaCost { get; set; }

    /// <summary>Which needs this action satisfies (NeedName → satisfaction amount).</summary>
    public Dictionary<string, double> SatisfiedNeeds { get; set; } = new();

    /// <summary>Required minimum stat values (StatId → minValue).</summary>
    public Dictionary<int, double> RequiredStats { get; set; } = new();
}

public static class ActionCatalog
{
    // ── 30 BASIC ACTIONS ────────────────────────────────────────────────────

    public static readonly GameAction[] Basic =
    {
        new() { Id=1,  Name="Добыть еду",         Category=ActionCategory.Basic, StaminaCost=15,
                Description="Ищет пищу на улице или в зданиях.",
                SatisfiedNeeds=new(){["Еда"]=25} },
        new() { Id=2,  Name="Набрать воды",        Category=ActionCategory.Basic, StaminaCost=10,
                Description="Собирает питьевую воду.",
                SatisfiedNeeds=new(){["Вода"]=30} },
        new() { Id=3,  Name="Поспать",             Category=ActionCategory.Basic, StaminaCost=-30,
                Description="Восстанавливает силы и закрывает потребность во сне.",
                SatisfiedNeeds=new(){["Сон"]=40, ["Отдых"]=20} },
        new() { Id=4,  Name="Разжечь огонь",       Category=ActionCategory.Basic, StaminaCost=8,
                Description="Добывает тепло для группы.",
                SatisfiedNeeds=new(){["Тепло"]=35} },
        new() { Id=5,  Name="Умыться",             Category=ActionCategory.Basic, StaminaCost=5,
                Description="Базовая гигиена.",
                SatisfiedNeeds=new(){["Гигиена"]=30} },
        new() { Id=6,  Name="Посетить туалет",     Category=ActionCategory.Basic, StaminaCost=2,
                Description="Удовлетворяет физиологическую нужду.",
                SatisfiedNeeds=new(){["Туалет"]=50} },
        new() { Id=7,  Name="Осмотреться",         Category=ActionCategory.Basic, StaminaCost=5,
                Description="Проверяет периметр, снижает тревогу.",
                SatisfiedNeeds=new(){["Безопасность"]=20} },
        new() { Id=8,  Name="Отдохнуть",           Category=ActionCategory.Basic, StaminaCost=-15,
                Description="Короткий отдых без сна.",
                SatisfiedNeeds=new(){["Отдых"]=30} },
        new() { Id=9,  Name="Лечиться",            Category=ActionCategory.Basic, StaminaCost=5,
                Description="Использует медикаменты для восстановления здоровья.",
                SatisfiedNeeds=new(){["Здоровье"]=25} },
        new() { Id=10, Name="Поговорить",          Category=ActionCategory.Basic, StaminaCost=5,
                Description="Общение с другими выжившими.",
                SatisfiedNeeds=new(){["Социальность"]=30} },
        new() { Id=11, Name="Собрать дрова",       Category=ActionCategory.Basic, StaminaCost=12,
                Description="Заготавливает древесное топливо." },
        new() { Id=12, Name="Обыскать здание",     Category=ActionCategory.Basic, StaminaCost=18,
                Description="Ищет ресурсы в постройках." },
        new() { Id=13, Name="Починить снаряжение", Category=ActionCategory.Basic, StaminaCost=10,
                Description="Восстанавливает инструменты и оружие." },
        new() { Id=14, Name="Приготовить пищу",    Category=ActionCategory.Basic, StaminaCost=8,
                Description="Улучшает еду: повышает её сытность.",
                SatisfiedNeeds=new(){["Еда"]=10} },
        new() { Id=15, Name="Построить укрытие",   Category=ActionCategory.Basic, StaminaCost=20,
                Description="Возводит временную защиту." },
        new() { Id=16, Name="Нести охрану",        Category=ActionCategory.Basic, StaminaCost=10,
                Description="Дежурит на посту, снижает риск нападения.",
                SatisfiedNeeds=new(){["Безопасность"]=15} },
        new() { Id=17, Name="Изучить территорию",  Category=ActionCategory.Basic, StaminaCost=14,
                Description="Разведывает соседние локации.",
                RequiredStats=new(){[4]=30} },
        new() { Id=18, Name="Обменяться",          Category=ActionCategory.Basic, StaminaCost=5,
                Description="Торгует ресурсами с другим NPC.",
                SatisfiedNeeds=new(){["Социальность"]=10} },
        new() { Id=19, Name="Тренироваться",       Category=ActionCategory.Basic, StaminaCost=20,
                Description="Физические упражнения, развивает стат Сила/Выносливость." },
        new() { Id=20, Name="Записать заметки",    Category=ActionCategory.Basic, StaminaCost=3,
                Description="Документирует события в памяти." },
        new() { Id=21, Name="Починить крышу",      Category=ActionCategory.Basic, StaminaCost=15,
                Description="Улучшает жилищные условия, снижает потребность в Тепле." },
        new() { Id=22, Name="Убраться",            Category=ActionCategory.Basic, StaminaCost=8,
                Description="Санитарная обработка места жительства.",
                SatisfiedNeeds=new(){["Гигиена"]=15} },
        new() { Id=23, Name="Помолиться",          Category=ActionCategory.Basic, StaminaCost=3,
                Description="Повышает Веру на небольшую величину.",
                SatisfiedNeeds=new(){["Безопасность"]=10} },
        new() { Id=24, Name="Учиться",             Category=ActionCategory.Basic, StaminaCost=6,
                Description="Читает, слушает опытных, развивает Память/Логику." },
        new() { Id=25, Name="Перевязать рану",     Category=ActionCategory.Basic, StaminaCost=5,
                Description="Быстрая медицинская помощь.",
                SatisfiedNeeds=new(){["Здоровье"]=15} },
        new() { Id=26, Name="Наблюдать",           Category=ActionCategory.Basic, StaminaCost=4,
                Description="Следит за окрестностями, пополняет память." },
        new() { Id=27, Name="Раздобыть лекарства", Category=ActionCategory.Basic, StaminaCost=16,
                Description="Ищет медикаменты." },
        new() { Id=28, Name="Поиграть",            Category=ActionCategory.Basic, StaminaCost=5,
                Description="Развлечение, снижает напряжение.",
                SatisfiedNeeds=new(){["Отдых"]=15} },
        new() { Id=29, Name="Помочь соседу",       Category=ActionCategory.Basic, StaminaCost=10,
                Description="Оказывает помощь другому NPC, повышает Доверие.",
                SatisfiedNeeds=new(){["Социальность"]=15} },
        new() { Id=30, Name="Патрулировать",       Category=ActionCategory.Basic, StaminaCost=12,
                Description="Охраняет территорию.",
                SatisfiedNeeds=new(){["Безопасность"]=20} },
    };

    // ── 30 SPECIAL ACTIONS (требуют специализации или высоких статов) ───────

    public static readonly GameAction[] Special =
    {
        new() { Id=101, Name="Зварить самогон",       Category=ActionCategory.Special, StaminaCost=10,
                Description="Производит алкоголь.",
                SatisfiedNeeds=new(){["Алкоголь"]=40},
                RequiredStats=new(){[18]=40} },
        new() { Id=102, Name="Обустроить комфорт",    Category=ActionCategory.Special, StaminaCost=12,
                Description="Улучшает бытовые условия.",
                SatisfiedNeeds=new(){["Комфорт"]=35} },
        new() { Id=103, Name="Организовать развлечение",Category=ActionCategory.Special, StaminaCost=8,
                Description="Устраивает досуг для группы.",
                SatisfiedNeeds=new(){["Развлечения"]=40} },
        new() { Id=104, Name="Медитировать",          Category=ActionCategory.Special, StaminaCost=-10,
                Description="Глубокое расслабление, восстанавливает чакру.",
                SatisfiedNeeds=new(){["Медитация"]=50},
                RequiredStats=new(){[21]=35} },
        new() { Id=105, Name="Тренировка боевых навыков",Category=ActionCategory.Special, StaminaCost=25,
                Description="Развивает боевые статы.",
                SatisfiedNeeds=new(){["Спорт"]=40},
                RequiredStats=new(){[1]=40,[3]=40} },
        new() { Id=106, Name="Играть на инструменте", Category=ActionCategory.Special, StaminaCost=5,
                Description="Музыкальное выступление, поднимает мораль.",
                SatisfiedNeeds=new(){["Музыка"]=50} },
        new() { Id=107, Name="Рисовать",              Category=ActionCategory.Special, StaminaCost=4,
                Description="Творческое самовыражение.",
                SatisfiedNeeds=new(){["Рисование"]=50},
                RequiredStats=new(){[18]=30} },
        new() { Id=108, Name="Готовить изысканно",    Category=ActionCategory.Special, StaminaCost=10,
                Description="Кулинарный эксперимент, улучшает качество пищи.",
                SatisfiedNeeds=new(){["Кулинария"]=45, ["Еда"]=15},
                RequiredStats=new(){[18]=25} },
        new() { Id=109, Name="Ухаживать за растениями",Category=ActionCategory.Special, StaminaCost=8,
                Description="Садоводство, создаёт возобновляемый источник еды.",
                SatisfiedNeeds=new(){["Садоводство"]=50} },
        new() { Id=110, Name="Рыбачить",              Category=ActionCategory.Special, StaminaCost=10,
                Description="Добывает рыбу, удовлетворяет еду и хобби.",
                SatisfiedNeeds=new(){["Рыбалка"]=50, ["Еда"]=10} },
        new() { Id=111, Name="Охотиться",             Category=ActionCategory.Special, StaminaCost=20,
                Description="Охота на зверя.",
                SatisfiedNeeds=new(){["Охота"]=50, ["Еда"]=20},
                RequiredStats=new(){[1]=35,[2]=35} },
        new() { Id=112, Name="Коллекционировать",     Category=ActionCategory.Special, StaminaCost=8,
                Description="Собирает предметы, удовлетворяет увлечение.",
                SatisfiedNeeds=new(){["Коллекционирование"]=45} },
        new() { Id=113, Name="Исследовать развалины",  Category=ActionCategory.Special, StaminaCost=20,
                Description="Экспедиция в опасные зоны.",
                SatisfiedNeeds=new(){["Путешествия"]=30, ["Адреналин"]=25},
                RequiredStats=new(){[3]=40,[9]=35} },
        new() { Id=114, Name="Рискованная вылазка",   Category=ActionCategory.Special, StaminaCost=22,
                Description="Экстремально опасная операция.",
                SatisfiedNeeds=new(){["Адреналин"]=55},
                RequiredStats=new(){[7]=45} },
        new() { Id=115, Name="Выступить перед группой",Category=ActionCategory.Special, StaminaCost=7,
                Description="Речь или демонстрация, повышает Признание.",
                SatisfiedNeeds=new(){["Признание"]=50},
                RequiredStats=new(){[14]=40} },
        new() { Id=116, Name="Побыть в одиночестве",  Category=ActionCategory.Special, StaminaCost=-5,
                Description="Восстановление без контакта с людьми.",
                SatisfiedNeeds=new(){["Одиночество"]=55} },
        new() { Id=117, Name="Сыграть в карты",       Category=ActionCategory.Special, StaminaCost=5,
                Description="Азартная игра.",
                SatisfiedNeeds=new(){["Азартные игры"]=50} },
        new() { Id=118, Name="Провести ритуал",       Category=ActionCategory.Special, StaminaCost=8,
                Description="Религиозная или мистическая практика.",
                SatisfiedNeeds=new(){["Ритуалы"]=50},
                RequiredStats=new(){[17]=35} },
        new() { Id=119, Name="Наставлять новичка",    Category=ActionCategory.Special, StaminaCost=10,
                Description="Обучает другого NPC, повышает Доверие и Признание.",
                SatisfiedNeeds=new(){["Наставничество"]=50},
                RequiredStats=new(){[22]=40} },
        new() { Id=120, Name="Провести исследование", Category=ActionCategory.Special, StaminaCost=8,
                Description="Научный или технический анализ.",
                SatisfiedNeeds=new(){["Исследования"]=50},
                RequiredStats=new(){[12]=40,[20]=35} },
        new() { Id=121, Name="Танцевать",             Category=ActionCategory.Special, StaminaCost=10,
                Description="Танец, поднимает настроение и снижает страх.",
                SatisfiedNeeds=new(){["Танцы"]=50} },
        new() { Id=122, Name="Петь",                  Category=ActionCategory.Special, StaminaCost=5,
                Description="Пение в одиночку или для группы.",
                SatisfiedNeeds=new(){["Пение"]=50} },
        new() { Id=123, Name="Мастерить",             Category=ActionCategory.Special, StaminaCost=15,
                Description="Создаёт предметы ручной работы.",
                SatisfiedNeeds=new(){["Ремесло"]=50},
                RequiredStats=new(){[2]=35} },
        new() { Id=124, Name="Синтезировать вещество",Category=ActionCategory.Special, StaminaCost=12,
                Description="Химическое производство (лекарства, взрывчатка).",
                SatisfiedNeeds=new(){["Химия"]=50},
                RequiredStats=new(){[12]=50,[20]=45} },
        new() { Id=125, Name="Составить гороскоп",    Category=ActionCategory.Special, StaminaCost=4,
                Description="Астрологическая практика, снижает тревогу у суеверных.",
                SatisfiedNeeds=new(){["Астрология"]=50},
                RequiredStats=new(){[17]=30} },
        new() { Id=126, Name="Починить технику",      Category=ActionCategory.Special, StaminaCost=14,
                Description="Ремонт электронных и механических устройств.",
                SatisfiedNeeds=new(){["Техника"]=45},
                RequiredStats=new(){[11]=40,[26]=35} },
        new() { Id=127, Name="Прочитать книгу",       Category=ActionCategory.Special, StaminaCost=3,
                Description="Интеллектуальное чтение.",
                SatisfiedNeeds=new(){["Книги"]=50},
                RequiredStats=new(){[13]=25} },
        new() { Id=128, Name="Шопинг/Мародёрство",   Category=ActionCategory.Special, StaminaCost=14,
                Description="Поиск товаров в заброшенных магазинах.",
                SatisfiedNeeds=new(){["Шопинг"]=50} },
        new() { Id=129, Name="Навестить парикмахера", Category=ActionCategory.Special, StaminaCost=3,
                Description="Уход за внешностью, повышает уверенность.",
                SatisfiedNeeds=new(){["Парикмахер"]=50} },
        new() { Id=130, Name="Заниматься сексом",     Category=ActionCategory.Special, StaminaCost=10,
                Description="Интимная близость с партнёром.",
                SatisfiedNeeds=new(){["Секс"]=60} },
    };
}
